services:
  - type: web
    name: portfolio-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDirectory: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false

  - type: web
    name: portfolio-client
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html